=== duggerd/p25-wireline/p25-wireline/issi-tools/dtd/globaltopology.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- 
The ISSI emulation consists of multiple rfsss, su's and groups.  
The global topology configuration file specifies the SUs and group
assignments for the given test suite. You will have to configure
your unit under test to be aware of these user and group
IDs, home RFSSs etc. The global topology references
RFSS entities that are defined in the associated
"systemtopology.xml" file. Note that the Rfss IDs reference
those that are defined in the "systemtopology.xml" and these
are also referenced in each individual test case 
topology.xml file. Therefore these names should
not be changed for a given test suite.


@title Global Topology Specification
@root global-topology
-->

<!-- The top level tag for the configuration of global topology. The global topology is the global assignment of SUs and Groups to RFSSs across all 
tests int he system. You should configure your test system to be aware of the SU's and Gruoups specified in this file.
-->
<!ELEMENT global-topology (rfssconfig+,suconfig*,sgconfig*)>




<!--
@attr rfssName The RFSS name. This must refer to an 
		RFSS defined in the associated systemtopology.xml 
		file. Do not change this assignment for a given
		test suite otherwise the test scripts that 
		refer to this name may break.
@attr selftestPort The port used for self test trace generation.
		Selftest involves running the scenario for each emulated
		RFSS using localhost (127.0.0.1) and selftestPort for 
		SIP signaling call setup. The generated traces is
		IP address and port independent. This can be any
		random integer.
-->

<!ATTLIST rfssconfig 
	rfssName 			ID    #REQUIRED
	selftestPort                    CDATA #REQUIRED
>

<!-- This defines the configuration of an RFSS. The name must match that
specified in systemconfig. -->
<!ELEMENT rfssconfig  EMPTY >


<!-- Defines an SU. An SU has an associated User Profile which the Home
RFSS keeps. This is initialized with default values that can be overriden
in the test topology file for the given test. -->
<!ELEMENT suconfig EMPTY>

<!-- A group configuration tag. A group is statically configured  with
one or more subscribers. Note that the subscribers are specified as
Subscriber units. A group  has a group profile which is initialized
with default values which can be overriden for the given group in the
test topology file.
-->

<!ELEMENT sgconfig EMPTY>



<!-- 
@attr suName SU name. This is a uniqe symbolic identifier for the su.

@attr suId SU numeric unit id as defined in TIA 102 BACA (specified in Hex)

@attr homeRfssName Home RFSS name (must refer to a rfss referenced in this file 
		and defined in systemtopology.xml ).

@attr servingRfssName Serving RFSS name

-->
<!ATTLIST suconfig
	suName					ID    #REQUIRED
	suId					CDATA #REQUIRED
	homeRfssName				IDREF #REQUIRED
	servingRfssName				IDREF #REQUIRED
>


<!-- 
@attr groupName its unique symolic name. Note that this name should
	not be changed otherwise the tests that refer to this group
	will break. Note that subscribers are sepcified on a per test
	basis. See the topologyconfig.xml for a given test to see
	subscriber assignments.
@attr sgId The group ID ( as defined in TIA 102 BACA) specified in Hex. 
	You can assign any unique value you want to this filed.
@attr homeRfssName The name of the Home RFSS of this group. The home
	Rfss must be defined in the systemtopology file associated
	with the test suite.
-->
<!ATTLIST sgconfig
	groupName				ID    #REQUIRED
	sgId					CDATA #REQUIRED
	homeRfssName				IDREF #REQUIRED
>

=== duggerd/p25-wireline/p25-wireline/issi-tools/schema/xml/globaltopology.xml
<?xml version="1.0" ?>
<!DOCTYPE global-topology SYSTEM "http://www-x.antd.nist.gov:8080/p25/issi-emulator/dtd/globaltopology.dtd">
<global-topology> 

<rfssconfig
	rfssName="rfss_5"
	selftestPort ="4423"
/>
<rfssconfig
	rfssName="rfss_4"
	selftestPort ="4234"
/>
<rfssconfig
	rfssName="rfss_3"
	selftestPort ="4231"
/>
<rfssconfig
	rfssName="rfss_2"
	selftestPort ="4312"
/>
<rfssconfig
	rfssName="rfss_1"
	selftestPort ="4123"
/>

<suconfig
	suId="111"
	suName="su_111"
	homeRfssName="rfss_1"
	servingRfssName="rfss_1"
/>
<suconfig
	suId="211"
	suName="su_211"
	homeRfssName="rfss_2"
	servingRfssName="rfss_1"
/>
<suconfig
	suId="25"
	suName="su_25"
	homeRfssName="rfss_2"
	servingRfssName="rfss_5"
/>
<suconfig
	suId="22"
	suName="su_22"
	homeRfssName="rfss_2"
	servingRfssName="rfss_2"
/>
<suconfig
	suId="21"
	suName="su_21"
	homeRfssName="rfss_2"
	servingRfssName="rfss_1"
/>
<suconfig
	suId="14d"
	suName="su_333"
	homeRfssName="rfss_3"
	servingRfssName="rfss_3"
/>
<suconfig
	suId="121"
	suName="su_121"
	homeRfssName="rfss_1"
	servingRfssName="rfss_2"
/>
<suconfig
	suId="13"
	suName="su_13"
	homeRfssName="rfss_1"
	servingRfssName="rfss_3"
/>
<suconfig
	suId="222"
	suName="su_222"
	homeRfssName="rfss_2"
	servingRfssName="rfss_2"
/>
<suconfig
	suId="12"
	suName="su_12"
	homeRfssName="rfss_1"
	servingRfssName="rfss_2"
/>
<suconfig
	suId="11"
	suName="su_11"
	homeRfssName="rfss_1"
	servingRfssName="rfss_1"
/>
<suconfig
	suId="34"
	suName="su_34"
	homeRfssName="rfss_3"
	servingRfssName="rfss_4"
/>
<suconfig
	suId="33"
	suName="su_33"
	homeRfssName="rfss_3"
	servingRfssName="rfss_3"
/>

<sgconfig
	groupName="group_1"
	sgId="1"
	homeRfssName="rfss_1"
/>
<sgconfig
	groupName="group_2"
	sgId="5"
	homeRfssName="rfss_2"
/>
<sgconfig
	groupName="group_3"
	sgId="3"
	homeRfssName="rfss_3"
/>

</global-topology>

=== duggerd/p25-wireline/p25-wireline/issi-tools/unit-test/globaltopology.xml
<?xml version="1.0" ?>
<!DOCTYPE issi-tester-config SYSTEM "http://www-x.antd.nist.gov:8080/p25/issi-emulator/dtd/globaltopology.dtd">
<global-topology>

<!-- This is a global topology file. It defines SUs and Groups 
The RFSS ids in the file refer to the values in systemtopology.xml,
The following are random ports.  Each SU and group defined
here has a default SU / Group profile. They can be overriden
in the topologyconfig.xml file for each test case.

IMPORTANT:  DO NOT change the RFSS names in this script and the SU 
names in this script. You are free to change the ID assignments and 
port assignments. 
-->

<rfssconfig
	rfssName= "rfss_1"
	selftestPort = "4123"
/>

<rfssconfig
	rfssName = "rfss_2"
	selftestPort = "4312"
/>
<rfssconfig
	rfssName="rfss_3"	
	selftestPort = "4231"
/>
<rfssconfig
	rfssName="rfss_4"	
	selftestPort = "4234"
/>
<rfssconfig
	rfssName="rfss_5"	
	selftestPort = "4423"
/>

<!-- Another SU homed and served at RFSS 1 -->
<suconfig
	suName		="su_11"
	suId		="11"
	homeRfssName 	="rfss_1"
	servingRfssName ="rfss_1"
/>


<!-- Another SU homed and served at RFSS 1 -->
<suconfig
	suName			="su_111"
	suId			="111"
	homeRfssName 	        ="rfss_1"
	servingRfssName         ="rfss_1"
/>


<!-- an su homed and served at rfss 3 -->
<suconfig
	suName			= "su_33"
	suId			= "33"
	homeRfssName 	        = "rfss_3"
	servingRfssName         = "rfss_3"
/>


<!-- an su homed and served at rfss 3 -->
<suconfig
	suName			="su_333"
	suId			="333"
	homeRfssName 	        ="rfss_3"
	servingRfssName         ="rfss_3"
/>


<!-- an su homed and served at rfss 2 -->
<suconfig
	suName			="su_22"
	suId			="22"
	homeRfssName 		= "rfss_2"
	servingRfssName 	= "rfss_2"
/>

<!-- another su homed and served at rfss 2 -->
<suconfig
	suName		="su_222"
	suId            ="222"
	homeRfssName    = "rfss_2"
	servingRfssName = "rfss_2"
/>

<!-- an su homed at 1 and served at 2 -->
<suconfig
	suName		="su_12"
	suId            ="12"
	homeRfssName    = "rfss_1"
	servingRfssName = "rfss_2"
/>
<!-- this is homed at 2 and served at 1 -->
<suconfig
	suName		="su_21"
	suId            ="21"
	homeRfssName    = "rfss_2"
	servingRfssName = "rfss_1"
/>

<suconfig
	suName		="su_13"
	suId            ="13"
	homeRfssName    = "rfss_1"
	servingRfssName = "rfss_3"
/>


<!-- has higher priority for u2u calls -->
<suconfig
	suName="su_34"
	suId="34"
	homeRfssName = "rfss_3"
	servingRfssName = "rfss_4"
/>

<!-- Group configurations. This is homed at the IUT -->
<sgconfig
	groupName= "group_1"
	sgId = "1"
	homeRfssName = "rfss_1"
/>

<sgconfig
	groupName= "group_2"
	sgId = "5"
	homeRfssName = "rfss_2"
/>

<sgconfig
	groupName= "group_3"
	sgId = "6"
	homeRfssName = "rfss_3"
/>

</global-topology>
